#!/bin/bash

# Set variables
    LOCALFILES="/mnt/github/jnmitch/centos/local-files"
    DB_STARTS_WITH="phabricator"
    DB_USER="root"
    DB_ROOT_PWD=$(< $LOCALFILES/password-mysql_root)
    DBS="$(mysql -u $DB_USER -p"$DB_ROOT_PWD" -Bse 'show databases')"

# Remove cloned git folders
    rm -rf /var/www/html/phacility

# Delete Phabricator tables from database
    for DB in $DBS; do
        if [[ "$DB" == $DB_STARTS_WITH* ]]; then
            echo "Deleting $DB"
            mysql -u $DB_USER -p"$DB_ROOT_PWD" -Bse "drop database $DB"
        fi
    done

# Restart database
    systemctl restart mariadb

# Remove vhost from apache
# Remove listen port from http.conf
# Stop/remove port in iptables

# Unset variables
    unset LOCALFILES
    unset DB_STARTS_WITH
    unset DB_USER
    unset DB_ROOT_PWD
    unset DBS
    unset DB
