#!/bin/bash

# Auto-mount local shared folders on startup
    cat $INCLUDE/mount-folders >> /etc/fstab

# SELinux management tools
    yum install -y policycoreutils-python # for 'semanage permissive'

# Set timezone
    timedatectl set-timezone America/Denver

# Time synchronization
    yum install -y ntp
    systemctl start ntpd
    systemctl enable ntpd
