#!/bin/bash

# Set variable
    WEBMIN="/etc/webmin/miniserv.conf"

# Install EPEL Repo
    yum --enablerepo=extras install -y epel-release

# Create Webmin Repo
    cat $INCLUDE/webmin-repo > /etc/yum.repos.d/webmin.repo

# Install Webmin
    cd /tmp
    rpm --import http://www.webmin.com/jcameron-key.asc
    cd /
    yum check-update
    yum install -y webmin perl-Socket6

# Backup Webmin config
    cp $WEBMIN $WEBMIN.orig

# Change Webmin Port
    sed -i -e 's|port=10000|port=50505|' $WEBMIN
    sed -i -e 's|listen=10000|listen=50505|' $WEBMIN

# Start Webmin
    # systemctl start webmin
    /sbin/chkconfig webmin on
    systemctl enable webmin

# Unset variable
    unset WEBMIN
