#!/bin/bash

# Install MariaDB

  yum install -y mariadb-server mariadb

# Start MariaDB

  systemctl start mariadb.service
  systemctl enable mariadb.service

# Secure MySQL

  mysql_secure_installation
  # - Set root password? [Y/n] y
  #   - MySqL63
  # - Remove anonymous users? [Y/n] y
  # - Disallow root login remotely? [Y/n] y
  # - Remove test database and access to it? [Y/n] y
  # - Reload privilege tables now? [Y/n] y

