#!/bin/bash

    yum install -y httpd

    systemctl start httpd.service
    systemctl enable httpd.service

    nano /etc/httpd/conf/httpd.conf

# !!!AUTOMATE!!!
    <VirtualHost *:80>
    ServerAdmin root@localhost.phabricator
    ServerName localhost.phabricator
    DocumentRoot /var/www/html/phabricator/phabricator/webroot
    RewriteEngine on
    RewriteRule ^/rsrc/(.*)     -                       [L,QSA]
    RewriteRule ^/favicon.ico   -                       [L,QSA]
    RewriteRule ^(.*)$          /index.php?__path__=$1  [B,L,QSA]
    <Directory "/var/www/html/phabricator/phabricator/webroot">
        Order allow,deny
        Allow from all
    </Directory>
    </VirtualHost>
# !!!!!!!!

    systemctl restart httpd
    