#!/bin/bash

#################################################
# Common / Useful Commands                      #
#################################################

# Get IP address
    ip a

# State of the network
    nmcli d

# List all files
    ll

# List all files incl. hidden
    ls -Al

# List IPtables
    iptables -nL

# Details of reserved ports
    cat /etc/services

# CentOS veresion
    cat /etc/centos-release

# Kernel version
    uname -a

# Removes Windows end of line / carriage return for a given file
    sed -i 's/\r$//' /github/winfile

# Login to MySQL via Command Line
    mysql -u USERNAME -p

# Display a list of databases
    mysql> show databases;

# Access a specific database,
    mysql> use DBNAME;

# Open/listening ports
    lsof -i -P -n | grep LISTEN
    nmap -sT -O localhost ( or 0.0.0.0 )

# To change all the directories to 755 (drwxr-xr-x)
    find /opt/lampp/htdocs -type d -exec chmod 755 {} \;

# To change all the files to 644 (-rw-r--r--)
    find /opt/lampp/htdocs -type f -exec chmod 644 {} \;

"[[ tail -n 10 /var/log/mongodb/mongod.log ]]
[[ npm list --depth=0 ]]
[[ npm list -g --depth=0 ]]"