#!/bin/bash

# Set network for DHCP
    vi /etc/sysconfig/network-scripts/ifcfg-en*
        => ONBOOT=yes
    systemctl restart network

# Update yum
    yum -y update && yum -y upgrade; reboot # for kernal update and bash

# Install admin tools
    yum install -y nano git wget bzip2 which # for file activity

# Install development tools
    yum install -y gcc-c++ make kernel-devel; reboot # for mounting shared folders

# Create and mount cdrom
    mkdir /media/cdrom
    mount /dev/cdrom /media/cdrom
    /media/cdrom/VBoxLinuxAdditions.run

# Mount shared folder(s)
    mkdir /mnt/github
    mount –t vboxsf /Github /mnt/github # also exists at /media/sf_github

# Set variables
    BOOTER="/mnt/github/jnmitch/centos/boot"

# Change mounted file encoding
    sed -i 's/\r$//' $BOOTER/setup1
    sed -i 's/\r$//' $BOOTER/setup2

# Run install scripts
    bash $BOOTER/setup1
    bash $BOOTER/setup2
