#!/bin/bash

    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    ADMIN="/mnt/github/jnmitch/centos/setup/admin"
    export LOCAL="/mnt/github/jnmitch/centos/local"
    export INCLUDE="/mnt/github/jnmitch/centos/include"
    export SERVICE="/mnt/github/jnmitch/centos/service"
    export DB_ROOT_PASS=$(< $LOCAL/mysql-root-pass)

# Change mounted file encoding
    sed -i 's/\r$//' $ADMIN/system
    sed -i 's/\r$//' $ADMIN/network
    sed -i 's/\r$//' $ADMIN/ssh
    # sed -i 's/\r$//' $ADMIN/firewalld
    sed -i 's/\r$//' $ADMIN/iptables
    sed -i 's/\r$//' $ADMIN/webmin

# Run VM config scripts
    bash $ADMIN/system
    bash $ADMIN/network
    bash $ADMIN/ssh
    # bash $ADMIN/firewalld
    bash $ADMIN/iptables
    bash $ADMIN/webmin

# Permanently disable SELinux
    # sed -i "s|SELINUX=enforcing|SELINUX=disabled|" /etc/sysconfig/selinux

# Unset Variables
    unset CENTOS
    unset LOCAL
    unset INCLUDE
    unset SERVICE
    unset DB_ROOT_PASS

# Reboot server
    reboot
