#!/bin/bash

    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    LAMP="/mnt/github/jnmitch/centos/setup/lamp"
    export LOCAL="/mnt/github/jnmitch/centos/local"
    export INCLUDE="/mnt/github/jnmitch/centos/include"
    export SERVICE="/mnt/github/jnmitch/centos/service"
    export DB_ROOT_PWD=$(< $LOCAL/mysql-root-pass)

# Change mounted file encoding
    sed -i 's/\r$//' $LAMP/apache
    sed -i 's/\r$//' $LAMP/php
    sed -i 's/\r$//' $LAMP/mariadb
    sed -i 's/\r$//' $LAMP/phpmyadmin
    # sed -i 's/\r$//' $LAMP/phppgLAMP

# Run VM config scripts
    bash $LAMP/apache
    bash $LAMP/php
    bash $LAMP/mariadb
    bash $LAMP/phpmyadmin
    # bash $LAMPs/phppgLAMP
    
# Unset Variables
    unset SETUP
    unset LOCAL
    unset INCLUDE
    unset SERVICE
    unset DB_ROOT_PWD

# Reboot server
    reboot
    