#!/bin/bash

# Create and mount cdrom
    mkdir /media/cdrom
    mount /dev/cdrom /media/cdrom
    /media/cdrom/VBoxLinuxAdditions.run

# Mount shared folder(s)
    mkdir /mnt/github
    mount –t vboxsf /Github /mnt/github # not needed: /Users/Jeff/...
    # also exists at /media/sf_github

# SSH
    # ssh -p 2424 jeff@localhost
