#!/bin/bash

    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    SETUP="/mnt/github/jnmitch/centos/setup"
    export LOCAL="/mnt/github/jnmitch/centos/local"
    export SERVICE="/mnt/github/jnmitch/centos/service"
    export DB_ROOT_PWD=$(< $LOCAL/mysql-root-pass)

# Change mounted file encoding
    sed -i 's/\r$//' $SETUP/mariadb
    sed -i 's/\r$//' $SETUP/phpmyadmin
    # sed -i 's/\r$//' $SETUP/phppgadmin

# Run VM config scripts
    bash $SETUP/mariadb
    bash $SETUP/phpmyadmin
    # bash $SETUPs/phppgadmin

# Unset Variables
    unset SETUP
    unset LOCAL
    unset SERVICE
    unset DB_ROOT_PWD

# Reboot server
    reboot
    