#!/bin/bash
# CONSIDER SSH AFTER REBOOT OF SETUP1

    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    SETUP="/mnt/github/jnmitch/centos/setup"
    export LOCAL="/mnt/github/jnmitch/centos/local"
    export INCLUDE="/mnt/github/jnmitch/centos/include"
    export SERVICE="/mnt/github/jnmitch/centos/service"
    export DB_ROOT_PWD=$(< $LOCAL/mysql-root-pass)

# Change mounted file encoding
    sed -i 's/\r$//' $SETUP/apache
    sed -i 's/\r$//' $SETUP/php

# Run VM config scripts
    bash $SETUP/apache
    bash $SETUP/php

# Unset Variables
    unset SETUP
    unset LOCAL
    unset INCLUDE
    unset SERVICE
    unset DB_ROOT_PWD

# Reboot server
    reboot
    