#!/bin/bash
# CONSIDER SSH AFTER REBOOT OF SETUP1

    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    SETUPFILES="/mnt/github/jnmitch/centos/setup"
    export LOCALFILES="/mnt/github/jnmitch/centos/local"
    export INCLUDE="/mnt/github/jnmitch/centos/include"
    export SERVICEFILES="/mnt/github/jnmitch/centos/service"
    export DB_ROOT_PWD=$(< $LOCALFILES/pass-mysql-root)

# Change mounted file encoding
    sed -i 's/\r$//' $SETUPFILES/apache
    sed -i 's/\r$//' $SETUPFILES/php

# Run VM config scripts
    bash $SETUPFILES/apache
    bash $SETUPFILES/php

# Unset Variables
    unset SETUPFILES
    unset LOCALFILES
    unset INCLUDE
    unset SERVICEFILES
    unset DB_ROOT_PWD

# Reboot server
    reboot
    