#!/bin/bash

    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    SETUP="/mnt/github/jnmitch/centos/setup"
    export LOCAL="/mnt/github/jnmitch/centos/local"
    export INCLUDE="/mnt/github/jnmitch/centos/include"
    export SERVICE="/mnt/github/jnmitch/centos/service"
    export DB_ROOT_PASS=$(< $LOCAL/mysql-root-pass)

# Change mounted file encoding
    sed -i 's/\r$//' $SETUP/system
    sed -i 's/\r$//' $SETUP/network
    sed -i 's/\r$//' $SETUP/ssh
    # sed -i 's/\r$//' $SETUP/firewalld
    sed -i 's/\r$//' $SETUP/iptables
    sed -i 's/\r$//' $SETUP/webmin

# Run VM config scripts
    bash $SETUP/system
    bash $SETUP/network
    bash $SETUP/ssh
    # bash $SETUP/firewalld
    bash $SETUP/iptables
    bash $SETUP/webmin

# Permanently disable SELinux
    # sed -i "s|SELINUX=enforcing|SELINUX=disabled|" /etc/sysconfig/selinux

# SSH
    # ssh -p 2424 jeff@localhost

# Unset Variables
    unset SETUP
    unset LOCAL
    unset INCLUDE
    unset SERVICE
    unset DB_ROOT_PASS

# Reboot server
    # CONSIDER SSH AFTER REBOOT OF SETUP1
    # reboot
