#!/bin/bash
    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set variables
    export LOCAL="/mnt/github/jnmitch/centos/local"
    export INCLUDE="/mnt/github/jnmitch/centos/include"
    PATCH="/mnt/github/jnmitch/centos/patch"

# Change mounted file encoding
    # sed -i 's/\r$//' $PATCH/20170326
    # sed -i 's/\r$//' $PATCH/20170327
    # sed -i 's/\r$//' $PATCH/20170328

# Run install scripts
    # bash $PATCH/20170326
    # bash $PATCH/20170327
    # bash $PATCH/20170328

# Unset variables
    unset LOCAL
    unset INCLUDE
    unset PATCH

# Restart server
    reboot
    