#!/bin/bash

# Set variable
    WEBMIN="/etc/webmin/miniserv.conf"

# Install EPEL Repo
    yum --enablerepo=extras install -y epel-release

# Create Webmin Repo
    cat $LOCALFILES/settings-webmin_repo > /etc/yum.repos.d/webmin.repo

# Install Webmin
    cd /tmp
    rpm --import http://www.webmin.com/jcameron-key.asc
    cd /
    yum check-update
    yum install -y webmin perl-Socket6

# Change Webmin Port
    # duplicate config file
        cp $WEBMIN $WEBMIN.orig
    # replace port on 1st line
        # OLD: sed -i '1s/^/port=50505\n/' $WEBMIN
        sed -i -e 's|port=10000|port=50505|' $WEBMIN
    # replace listen on 22nd line
        # OLD: sed -i '22s/^/listen=50505\n/' $WEBMIN
        sed -i -e 's|listen=10000|listen=50505|' $WEBMIN

# Start Webmin
    chkconfig webmin on
    systemctl start webmin

# Unset variable
    unset WEBMIN
