#!/bin/bash

# Set variable
    export PHP="/etc/php.ini"
    # APC="/etc/php.d/apcu.ini"

# Install PHP 5.4.16 and dependencies (for Phabricator)
    yum install -y php php-cli php-common php-gd php-mbstring php-mysql php-apc php-process # php-devel pcre-devel
    # pecl install apc --force

# Configure php-apc for Phabricator
    # cp $APC $APC.orig
    # sed -i "s|;apc.enable_cli=0|apc.enable_cli=1|" $APC # line 9
    # sed -i "s|;apc.shm_size=32M|apc.shm_size=1024M|" $APC # line 19
    # sed -i "s|;apc.ttl=0|apc_ttl=72000|" $APC # line 23
    # sed -i "s|;apc.gc_ttl=3600|apc.gc_ttl=3600|" $APC # line 27
    # # sed -i "s|;apc.user_entries_hint=4096|apc.user_entries_hint=20000|" $APC # line 39
    # # echo "extension=apc.so" > /etc/php.d/apc.ini

# Backup original file
    cp $PHP $PHP.orig

# Modify settings
    sed -i "s|expose_php = On|expose_php = Off|" $PHP # line 375
    sed -i "s|max_execution_time = 30|max_execution_time = 300|" $PHP # line 384
    sed -i "s|max_input_time = 60|max_input_time = 120|" $PHP # line 394
    sed -i "s|post_max_size = 8M|post_max_size = 105M|" $PHP # line 672
    sed -i "s|;always_populate_raw_post_data = On|always_populate_raw_post_data = -1|" $PHP # line 698 # for Phabricator setup error
    sed -i "s|upload_max_filesize = 2M|upload_max_filesize = 100M|" $PHP # line 800
    sed -i "s|;date.timezone =|date.timezone = America/Denver|" $PHP # line 878
    sed -i "s|mysql.default_password =|;mysql.default_password =|" $PHP # line 1108

# Test PHP
    echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
    # => http://yourdomain.com/phpinfo.php

# Test APC
    wget -O /var/www/html/apcinfo.php 'http://git.php.net/?p=pecl/caching/apc.git;a=blob_plain;f=apc.php'
    sed -i "s|defaults('ADMIN_USERNAME','apc'); 			// Admin Username|defaults('ADMIN_USERNAME','apcadmin'); 		// Admin Username|" /var/www/html/apcinfo.php # line 41
    sed -i "s|defaults('ADMIN_PASSWORD','password');  	// Admin Password - CHANGE THIS TO ENABLE!!!|defaults('ADMIN_PASSWORD','@PC@dm!n');  	// Admin Password|" /var/www/html/apcinfo.php # line 42
    # => http://yourdomain.com/apcinfo.php
    
    # creating file JUST BECAUSE
    # printf ";Enable APC extension module\nextension=apc.so" > /etc/php.d/apc.ini

# Unset variable
    # unset APC
