#!/bin/bash
    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set Variables
    SETUPFILES="/mnt/github/jnmitch/centos/setup-files"
    export LOCALFILES="/mnt/github/jnmitch/centos/local-files"
    export SERVICEFILES="/mnt/github/jnmitch/centos/service-files"
    export DB_ROOT_PWD=$(< $LOCALFILES/password-mysql_root)

# System
    sed -i 's/\r$//' $SETUPFILES/setup-system
    bash $SETUPFILES/setup-system

# Network
    sed -i 's/\r$//' $SETUPFILES/setup-network
    bash $SETUPFILES/setup-network

# Firewall
    sed -i 's/\r$//' $SETUPFILES/setup-firewall
    bash $SETUPFILES/setup-firewall

# Webmin
    sed -i 's/\r$//' $SETUPFILES/setup-webmin
    bash $SETUPFILES/setup-webmin

# MySQL (MariaDB)
    sed -i 's/\r$//' $SETUPFILES/setup-mysql
    bash $SETUPFILES/setup-mysql

# Apache
    sed -i 's/\r$//' $SETUPFILES/setup-apache
    bash $SETUPFILES/setup-apache

# PHP
    sed -i 's/\r$//' $SETUPFILES/setup-php
    bash $SETUPFILES/setup-php

# phpMyAdmin
    sed -i 's/\r$//' $SETUPFILES/setup-phpmyadmin
    bash $SETUPFILES/setup-phpmyadmin

# phpPgAdmin
    # # sed -i 's/\r$//' $SETUPFILES/setup-phppgadmin
    # # bash $SETUPFILES/setup-phppgadmin

# Phabricator
    sed -i 's/\r$//' $SETUPFILES/setup-phabricator
    bash $SETUPFILES/setup-phabricator

# Unset Variables
    unset SETUPFILES
    unset LOCALFILES
    unset SERVICEFILES
    unset DB_ROOT_PWD
    unset PHP
    unset APACHE

# reboot
