#!/bin/bash

# Set variable
    export PHAB="/var/www/html/phacility"
    PHAB_FILES="/srv/phabricator/files"
    DB_PHAB_PWD=$(< $LOCALFILES/password-mysql_phabricator)
    BASE_URI=$(hostname -I | cut -d" " -f 1) # set IP address as the base-uri when installing on VM

# Create Phabricator directories
    mkdir $PHAB # for application

    mkdir /srv/phabricator && mkdir /srv/phabricator/files # for local file storage used by the application
    chown -R apache:apache $PHAB_FILES
    
    mkdir /srv/github # for local repository path used by application
    chown -R apache:apache /srv/github

# Download Phabricator
    cd $PHAB
    git clone https://github.com/phacility/arcanist.git
    git clone https://github.com/phacility/libphutil.git
    git clone https://github.com/phacility/phabricator.git

    cd /
    chown -R apache:apache $PHAB

# Setup virtual host
    cat $LOCALFILES/apache-vhost_phabricator >> /etc/httpd/conf.d/vhosts.conf

# Modify Apache settings
    # sed -i "/Listen \*:80/a Listen \*:8080" $APACHE # line 42

# Restart the Apache service
    systemctl restart httpd

# Create Phabricator database user
    mysql --user=root --password=$DB_ROOT_PWD <<-EOF
    CREATE USER 'phabricator'@'localhost' IDENTIFIED BY '$DB_PHAB_PWD';
    GRANT ALL PRIVILEGES ON *.* TO 'phabricator'@'localhost';
    FLUSH PRIVILEGES;
EOF

# Configure MySQL for Phabricator
    sed -i "\|socket = /var/lib/mysql/mysql.sock|a max_allowed_packet=33554432" /etc/my.cnf
    sed -i '\|max_allowed_packet=33554432|{x;p;x;}' /etc/my.cnf # add space before
    sed -i "\|max_allowed_packet=33554432|a sql_mode=STRICT_ALL_TABLES" /etc/my.cnf
    sed -i "\|sql_mode=STRICT_ALL_TABLES|a ft_stopword_file=$PHAB/phabricator/resources/sql/stopwords.txt" /etc/my.cnf
    sed -i "\|ft_stopword_file=$PHAB/phabricator/resources/sql/stopwords.txt|a ft_min_word_len=3" /etc/my.cnf
    sed -i "\|ft_min_word_len=3|a innodb_buffer_pool_size=800M" /etc/my.cnf # set to 40% of total RAM # cat /prov/meminfo ... Hugepagesize: 2048 kB

# Setup the MariaDB credentials
    cd $PHAB/phabricator

    ./bin/config set mysql.host localhost
    ./bin/config set mysql.port 3306
    ./bin/config set mysql.user phabricator
    ./bin/config set mysql.pass $DB_PHAB_PWD

# Run the storage upgrade script and load the database schema
    ./bin/storage upgrade --force

# Restart database
    systemctl restart mariadb

# Configure Phabricator
    ./bin/config set phabricator.base-uri http://$BASE_URI
    ./bin/search index --all --force --background # rebuild search index
    ./bin/config done reindex # to clear the setup warning
    # ./bin/config set security.alternate-file-domain <domain> # link to a CDN
    ./bin/config set storage.local-disk.path $PHAB_FILES

# Create service for PHD daemon
    cat $SERVICEFILES/service-phabricator_phd > /lib/systemd/system/phabricator-phd.service
    sed -i "s/\${PHAB}/$PHAB/" /lib/systemd/system/phabricator-phd.service

# Start daemon so that it can do the required background tasks
    systemctl enable phabricator-phd
    chown -R apache:apache /var/tmp/phd/pid
    systemctl start phabricator-phd
    # ./bin/phd start # logs will appear in "var/tmp/phd/log/daemons.log"

# Unset variable
    unset PHAB
    unset PHAB_FILES
    unset DB_PHAB_PWD
    unset BASE_URI
