#!/bin/bash
    set -e # exit immediately if a command exits with a non-zero status
    set -x # print commands and their arguments as they are executed
    set -u # treat unset variables as an error when substituting

# Set variables
    LOCALFILES="/mnt/github/jnmitch/centos/local"
    DNS1=$(nmcli device show | grep IP4.DNS | awk '{print $2}')
    GATEWAY=$(route -n | grep 'UG[ \t]' | awk '{print $2}')
    IPADDR=$(hostname -I | awk '{print $1}') 
    DEVICENAME=$(nmcli device show | grep GENERAL.DEVICE | awk 'NR==1{print $2}')
    # UUIDNEW=$(uuidgen echo "${!DEVICENAME}")
    IFCFG="/etc/sysconfig/network-scripts/ifcfg-enp*"

# Install network tools
    yum install -y net-tools

# Update hostname
    OLD_HOSTNAME="$(hostname)"
    NEW_HOSTNAME="$1"

        if [ -z "$NEW_HOSTNAME" ]; then
            echo -n "Please enter the new hostname: "
            read NEW_HOSTNAME < /dev/tty
        fi

        if [ -z "$NEW_HOSTNAME" ]; then
            echo "Error: No hostname entered. Exiting."
            exit 1
        fi

    echo "Changing hostname from $OLD_HOSTNAME to $NEW_HOSTNAME..."

    hostname "$NEW_HOSTNAME"

    sed -i "s/HOSTNAME=.*/HOSTNAME=$NEW_HOSTNAME/g" /etc/sysconfig/network

        if [ -n "$(grep "$OLD_HOSTNAME" /etc/hosts)" ]; then
            sed -i "s/$OLD_HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts
        else
            echo -e "$(hostname -I | awk '{ print $1 }')\t$NEW_HOSTNAME" >> /etc/hosts
        fi

    echo "Done."

    systemctl restart network

# Change network device UUID (if server was cloned)
    # sed -i "s/UUID=.*/UUID=$UUIDNEW/" $IFCFG
    sed -i "s/UUID=bd89ad9f-fdd0-41ab-9787-684b9fd1dd2e/UUID=$UUIDNEW/" $IFCFG # the UUID of SOAR-TEST1

# Static IP
    cat $LOCALFILES/network-staticip >> $IFCFG

    sed -i "s/\${DNS1}/$DNS1/" $IFCFG
    sed -i "s/\${GATEWAY}/$GATEWAY/" $IFCFG
    sed -i "s/\${IPADDR}/$IPADDR/" $IFCFG

    systemctl restart network

# Unset variables
    unset LOCALFILES
    unset DNS1
    unset GATEWAY
    unset IPADDR
    unset DEVICENAME
    unset UUIDNEW
    unset IFCFG
