#!/bin/bash

# Set variable
    APACHE="/etc/httpd/conf/httpd.conf"

# Install Apache
    yum install -y httpd httpd-devel
    systemctl start httpd
    systemctl enable httpd

# Allow service http through firewalld (Permanent)
    # firewall-cmd --add-service=http
    # firewall-cmd -permanent -add-port=XXXX/tcp
    # firewall-cmd --reload

    # systemctl restart httpd

# Modify the default configuration in order to enhance security:
    cp /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.orig
    # sed -i 's|^|#&|g' /etc/httpd/conf.d/welcome.conf # hides welcome page

# Backup original file
    cp $APACHE $APACHE.orig

# Modify Apache settings
    sed -i "s|Listen 80|Listen \*:80|" $APACHE # line 42
    # sed -i "s|Options Indexes FollowSymLinks|Options FollowSymLinks|" $APACHE # line 144 (166?)

# Add virtual hosts
    cat $INCLUDE/apache-vhosts > /etc/httpd/conf.d/vhosts.conf

# FOR TESTING
    # mkdir -p /var/www/html/example.com/{public_html,logs}

# Restart Apache after modifying
    systemctl restart httpd

# Unset variable
    unset APACHE
