#!/bin/bash

# Create and mount cdrom
    mkdir /media/cdrom
    mount /dev/cdrom /media/cdrom
    /media/cdrom/VBoxLinuxAdditions.run

# Mount shared folder(s)
    mkdir /mnt/github
    mount –t vboxsf /github /mnt/github # also exists at /media/sf_github
