#!/bin/bash

# Install network tools
    yum install -y lsof nmap

# Network settings
    cat $INCLUDE/network-staticip >> /etc/sysconfig/network-scripts/ifcfg-enp*

# Set hostname variable
    HOSTY=$(hostname) # during boot, CentOS will load /etc/hostname contents in kernel's hostname setting. 
    # Absent /etc/hostname, it will get name from /etc/sysconfig/network

# Set IP address variable
    IPADDY=$(hostname -I | cut -d" " -f 1)

# Insert IP & hostname
    # sed -i '1c\$(hostname)' /etc/hostname
    sed -i '1i\'"$IPADDY   $HOSTY" /etc/hosts
    systemctl restart network

# Unset variables
    unset HOSTY
    unset IPADDY
