#!/bin/bash

# Set variable
    PMA="/etc/httpd/conf.d/phpMyAdmin.conf"

# Install phpMyAdmin
    yum install -y phpmyadmin

# Modify settings
    cp $PMA $PMA.orig

    sed -i "0,/Require ip 127.0.0.1/s//# Require ip 127.0.0.1/" $PMA # replace only the first occurance
    sed -i "0,/Require ip ::1/s//# Require ip ::1/" $PMA # replace only the first occurance
    sed -i "0,/<\/RequireAny>/s/<\/RequireAny>/\t Require all granted\n     &/" $PMA # replace only the first occurance

    # sed -i "s|Allow from 127.0.0.1|# Allow from 127.0.0.1|" $PMA
    # sed -i "s|Allow from ::1|# Allow from ::1|" $PMA
    # sed -i "/<\/RequireAny>/s/<\/RequireAny>/\t Require all granted\n     &/" $PMA
    # sed -i "s|Deny from All|# Deny from All|g" $PMA

# Modify Apache settings
    sed -i "s|Listen 80|Listen \*:80|" $APACHE # line 42
    sed -i "/Listen \*:80/a Listen \*:60606" $APACHE # line 42

# Setup virtual host
    cat $INCLUDE/apache-vhost-pma >> /etc/httpd/conf.d/vhosts.conf

# Restart Apache after modifying    
    systemctl restart httpd

# Unset variable
    unset PMA
